# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/harp
image: dockerimages/harp:latest

pages:
  cache:
    paths:
    - node_modules

  script:
  - npm install -g harp doctoc
  - doctoc --gitlab --title '**Contents**' .
  - harp compile ./ public
  artifacts:
    paths:
    - public
  only:
  - pages
